version: '3.8'

services:
  nginx:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/index.html:/usr/share/nginx/html/index.html
      - ./src/static:/usr/share/nginx/html/static
    ports:
      - "80:80"
    networks:
      - my_portfolio_resume_site_network

networks:
  my_portfolio_resume_site_network:
    name: my_portfolio_resume_site_network
